import { useFocusEffect } from "expo-router";
import { SymbolView } from "expo-symbols";
import { useVideoPlayer, type VideoPlayer, VideoView } from "expo-video";
import { useThemeColor } from "heroui-native";
import { type RefObject, useCallback, useEffect } from "react";
import { Text, View } from "react-native";
import Image from "@/components/ui/image";
import type { PickedMedia } from "./types";

export function MediaPreview({
	media,
	playerRef,
}: {
	media: PickedMedia;
	// Lets the parent pause the video before removing it (unmount is too late —
	// the native player is already released by then).
	playerRef: RefObject<VideoPlayer | null>;
}) {
	const muted = useThemeColor("muted");
	const aspectRatio =
		media.width && media.height ? media.width / media.height : undefined;

	return (
		<View className="mt-3 gap-3">
			{media.type === "video" ? (
				<VideoPreview
					uri={media.uri}
					aspectRatio={aspectRatio}
					playerRef={playerRef}
				/>
			) : (
				<Image
					source={{ uri: media.uri }}
					className="w-full rounded-xl bg-surface-tertiary"
					style={{ width: "100%", aspectRatio: aspectRatio ?? 1 }}
					contentFit="contain"
				/>
			)}
			<View className="flex-row items-center gap-2 px-1">
				<SymbolView name="sparkles" size={16} tintColor={muted} />
				<Text className="flex-1 text-muted-foreground text-sm">
					Title and description will be generated by AI
				</Text>
			</View>
		</View>
	);
}

function VideoPreview({
	uri,
	aspectRatio,
	playerRef,
}: {
	uri: string;
	aspectRatio?: number;
	playerRef: RefObject<VideoPlayer | null>;
}) {
	const player = useVideoPlayer(uri, (p) => {
		p.loop = true;
	});

	// Expose the live player so the parent's Remove handler can pause it.
	useEffect(() => {
		playerRef.current = player;
		return () => {
			if (playerRef.current === player) playerRef.current = null;
		};
	}, [player, playerRef]);

	// Stop audio when the modal is dismissed. The pause has to run on blur while
	// the native player is still alive — by unmount it's already released, so
	// guard the call in case it's gone (e.g. removed while still focused).
	useFocusEffect(
		useCallback(() => {
			return () => {
				try {
					player.pause();
				} catch {}
			};
		}, [player]),
	);

	return (
		<VideoView
			player={player}
			style={{ width: "100%", aspectRatio: aspectRatio ?? 1, borderRadius: 12 }}
		/>
	);
}
